name: genesis
channels:
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - genesis-world
      - rsl-rl-lib
      - torch
      - torchvision
      - tensorboard
      - PyYAML
      - pygame